[tools]
node = "22"
"npm:pnpm" = "9"
"npm:markdownlint-cli2" = "0.14"
"npm:@commitlint/cli" = "19"
"npm:@commitlint/config-conventional" = "19"
"pipx:yamllint" = "1.35"
"aqua:rhysd/actionlint" = "1.7"
"aqua:evilmartians/lefthook" = "1.7"
"aqua:tamasfe/taplo" = "0.9"
"aqua:zricethezav/gitleaks" = "8.21"
"aqua:koalaman/shellcheck" = "0.10"
"aqua:hadolint/hadolint" = "2.12"
go-task = "3"
